### PR TITLE
Dev mode

### PR DESCRIPTION
**Pull request by evelinec**
Converted guide to run in dev mode.

### CODE REVIEW

**Comment by NimG98** [comment]
Remove dependencies:

```
    <dependency>
        <groupId>com.sun.xml.bind</groupId>
        <artifactId>jaxb-core</artifactId>
        <version>2.3.0.1</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.sun.xml.bind</groupId>
        <artifactId>jaxb-impl</artifactId>
        <version>2.3.2</version>
        <scope>test</scope>
    </dependency>
```

**Comment by evelinec** [comment]
> Remove dependencies:
> 
> ```
>     <dependency>
>         <groupId>com.sun.xml.bind</groupId>
>         <artifactId>jaxb-core</artifactId>
>         <version>2.3.0.1</version>
>         <scope>test</scope>
>     </dependency>
>     <dependency>
>         <groupId>com.sun.xml.bind</groupId>
>         <artifactId>jaxb-impl</artifactId>
>         <version>2.3.2</version>
>         <scope>test</scope>
>     </dependency>
> ```

@NimG98 fixed in https://github.com/OpenLiberty/guide-microprofile-health/pull/90/commits/7ab08cbaa04beec80c92eafefd80475909198e44.

**Comment by evelinec** [comment]
@gkwan-ibm Can you review again? Thanks.

**Comment by gkwan-ibm** [comment]
dev content reviewed

**Pull request merged**
